"""Add width and height to PostImage

Revision ID: 9396154193ad
Revises: e61570584fb7
Create Date: 2026-02-14 11:35:15.927076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9396154193ad'
down_revision: Union[str, Sequence[str], None] = 'e61570584fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('post_images', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_images', 'height')
    op.drop_column('post_images', 'width')
    # ### end Alembic commands ###
