"""Initial migration

Revision ID: a124238fb08b
Revises: 
Create Date: 2026-02-13 21:33:28.030547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a124238fb08b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('LIKE', 'COMMENT', 'FOLLOW', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exif_data',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('camera_make', sa.String(length=50), nullable=True),
    sa.Column('camera_model', sa.String(length=50), nullable=True),
    sa.Column('lens', sa.String(length=100), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter_speed', sa.String(length=20), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('fuji_recipes',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('simulation', sa.Enum('PROVIA', 'VELVIA', 'ASTIA', 'CLASSIC_CHROME', 'PRO_NEG_HI', 'PRO_NEG_STD', 'CLASSIC_NEG', 'ETERNA', 'ETERNA_BLEACH_BYPASS', 'ACROS', 'MONOCHROME', 'SEPIA', 'NOSTALGIC_NEG', 'REALA_ACE', name='filmsimulation'), nullable=True),
    sa.Column('dynamic_range', sa.Enum('DR100', 'DR200', 'DR400', 'DR_P', 'DR_AUTO', name='dynamicrange'), nullable=True),
    sa.Column('wb', sa.String(length=50), nullable=True),
    sa.Column('wb_shift_r', sa.Integer(), nullable=True),
    sa.Column('wb_shift_b', sa.Integer(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('sharpness', sa.Integer(), nullable=True),
    sa.Column('highlights', sa.Integer(), nullable=True),
    sa.Column('shadows', sa.Integer(), nullable=True),
    sa.Column('grain', sa.String(length=50), nullable=True),
    sa.Column('color_chrome', sa.String(length=50), nullable=True),
    sa.Column('color_chrome_blue', sa.String(length=50), nullable=True),
    sa.Column('clarity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('fuji_recipes')
    op.drop_table('exif_data')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
