"""Add PostImage table and support multi-image posts

Revision ID: e61570584fb7
Revises: 8ebad71972c7
Create Date: 2026-02-13 23:13:09.362509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e61570584fb7'
down_revision: Union[str, Sequence[str], None] = '8ebad71972c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exif_data', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('exif_data', sa.Column('image_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('exif_data_ibfk_1'), 'exif_data', type_='foreignkey')
    op.create_foreign_key(None, 'exif_data', 'post_images', ['image_id'], ['id'])
    op.drop_column('exif_data', 'post_id')
    op.add_column('fuji_recipes', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('fuji_recipes', sa.Column('image_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('fuji_recipes_ibfk_1'), 'fuji_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'fuji_recipes', 'post_images', ['image_id'], ['id'])
    op.drop_column('fuji_recipes', 'post_id')
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=False))
    op.alter_column('posts', 'image_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('posts', 'likes_count')
    op.drop_column('posts', 'views_count')
    op.add_column('fuji_recipes', sa.Column('post_id', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'fuji_recipes', type_='foreignkey')
    op.create_foreign_key(op.f('fuji_recipes_ibfk_1'), 'fuji_recipes', 'posts', ['post_id'], ['id'])
    op.drop_column('fuji_recipes', 'image_id')
    op.drop_column('fuji_recipes', 'id')
    op.add_column('exif_data', sa.Column('post_id', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'exif_data', type_='foreignkey')
    op.create_foreign_key(op.f('exif_data_ibfk_1'), 'exif_data', 'posts', ['post_id'], ['id'])
    op.drop_column('exif_data', 'image_id')
    op.drop_column('exif_data', 'id')
    op.drop_table('post_images')
    # ### end Alembic commands ###
