"""feat(albums): add album and album_posts tables

Revision ID: e96f17da80fd
Revises: 794402e8815b
Create Date: 2026-02-17 17:57:05.730834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96f17da80fd'
down_revision: Union[str, Sequence[str], None] = '794402e8815b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('short_id', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='albumstatus'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_short_id'), 'albums', ['short_id'], unique=True)
    op.create_index(op.f('ix_albums_user_id'), 'albums', ['user_id'], unique=False)
    op.create_table('album_posts',
    sa.Column('album_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_posts')
    op.drop_index(op.f('ix_albums_user_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_short_id'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
