"""feat(notifications): add notification table

Revision ID: f2c6cff61595
Revises: 1354efe47363
Create Date: 2026-02-14 22:44:44.622229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2c6cff61595'
down_revision: Union[str, Sequence[str], None] = '1354efe47363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('post_id', sa.String(length=36), nullable=True))
    op.add_column('notifications', sa.Column('comment_id', sa.String(length=36), nullable=True))
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'comments', ['comment_id'], ['id'])
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('notifications', 'comment_id')
    op.drop_column('notifications', 'post_id')
    # ### end Alembic commands ###
